/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MocktimeProfiler_clock.h"

static const char* CMockString_tProfReadClock = "tProfReadClock";

typedef struct _CMOCK_tProfReadClock_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;

} CMOCK_tProfReadClock_CALL_INSTANCE;

static struct MocktimeProfiler_clockInstance
{
  char tProfReadClock_IgnoreBool;
  uint32_t tProfReadClock_FinalReturn;
  char tProfReadClock_CallbackBool;
  CMOCK_tProfReadClock_CALLBACK tProfReadClock_CallbackFunctionPointer;
  int tProfReadClock_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE tProfReadClock_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MocktimeProfiler_clock_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.tProfReadClock_CallInstance;
  if (Mock.tProfReadClock_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_tProfReadClock);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.tProfReadClock_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void MocktimeProfiler_clock_Init(void)
{
  MocktimeProfiler_clock_Destroy();
}

void MocktimeProfiler_clock_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint32_t tProfReadClock(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_tProfReadClock_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_tProfReadClock);
  cmock_call_instance = (CMOCK_tProfReadClock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.tProfReadClock_CallInstance);
  Mock.tProfReadClock_CallInstance = CMock_Guts_MemNext(Mock.tProfReadClock_CallInstance);
  if (Mock.tProfReadClock_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.tProfReadClock_FinalReturn;
    Mock.tProfReadClock_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.tProfReadClock_CallbackBool &&
      Mock.tProfReadClock_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.tProfReadClock_CallbackFunctionPointer(Mock.tProfReadClock_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.tProfReadClock_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.tProfReadClock_CallbackFunctionPointer(Mock.tProfReadClock_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void tProfReadClock_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tProfReadClock_CALL_INSTANCE));
  CMOCK_tProfReadClock_CALL_INSTANCE* cmock_call_instance = (CMOCK_tProfReadClock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tProfReadClock_CallInstance = CMock_Guts_MemChain(Mock.tProfReadClock_CallInstance, cmock_guts_index);
  Mock.tProfReadClock_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.tProfReadClock_IgnoreBool = (char)1;
}

void tProfReadClock_CMockStopIgnore(void)
{
  if(Mock.tProfReadClock_IgnoreBool)
    Mock.tProfReadClock_CallInstance = CMock_Guts_MemNext(Mock.tProfReadClock_CallInstance);
  Mock.tProfReadClock_IgnoreBool = (char)0;
}

void tProfReadClock_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_tProfReadClock_CALL_INSTANCE));
  CMOCK_tProfReadClock_CALL_INSTANCE* cmock_call_instance = (CMOCK_tProfReadClock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.tProfReadClock_CallInstance = CMock_Guts_MemChain(Mock.tProfReadClock_CallInstance, cmock_guts_index);
  Mock.tProfReadClock_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void tProfReadClock_AddCallback(CMOCK_tProfReadClock_CALLBACK Callback)
{
  Mock.tProfReadClock_IgnoreBool = (char)0;
  Mock.tProfReadClock_CallbackBool = (char)1;
  Mock.tProfReadClock_CallbackFunctionPointer = Callback;
}

void tProfReadClock_Stub(CMOCK_tProfReadClock_CALLBACK Callback)
{
  Mock.tProfReadClock_IgnoreBool = (char)0;
  Mock.tProfReadClock_CallbackBool = (char)0;
  Mock.tProfReadClock_CallbackFunctionPointer = Callback;
}

